### ISSUE TITLE
When I update my pkg I met some problem (It can work before #9)

### ISSUE THREAD

**Issue by jizizr** [psykhi/wordclouds#13]
```golang
package group

import (
	"bytes"
	// "fmt"
	"image/color"
	"image/png"

	// "os"
	// "time"

	"github.com/psykhi/wordclouds"
)

var DefaultColors = []color.RGBA{
	{0x1b, 0x1b, 0x1b, 0xff},
	{0x48, 0x48, 0x4B, 0xff},
	{0x59, 0x3a, 0xee, 0xff},
	{0x65, 0xCD, 0xFA, 0xff},
	{0x70, 0xD6, 0xBF, 0xff},
}

var boxes = wordclouds.Mask(
	"source/mask.png",
	600,
	600,
	color.RGBA{
		R: 0,
		G: 0,
		B: 0,
		A: 0,
	})

var colors = make([]color.Color, 0)

func init() {
	for _, c := range DefaultColors {
		colors = append(colors, c)
	}
}

func Rank(inputWords map[string]int) []byte {

	// Load words
	// inputWords := map[string]int{"消息": 42, "是啊": 30, "中文": 15, "也是": 10, "而我": 5, "撒旦": 11, "落后": 11}

	// Load config

	// start := time.Now()
	w := wordclouds.NewWordcloud(inputWords,
		wordclouds.FontFile("source/font.ttf"),
		wordclouds.FontMaxSize(125),
		wordclouds.FontMinSize(10),
		wordclouds.Colors(colors),
		wordclouds.MaskBoxes(boxes),
		wordclouds.Height(600),
		wordclouds.Width(600),
		wordclouds.RandomPlacement(false))

	// outputFile, _ := os.Create("test.png")
	buf := new(bytes.Buffer)
	// Encode takes a writer interface and an image interface
	// We pass it the File and the RGBA
	png.Encode(buf, w.Draw())

	// Don't forget to close files
	// outputFile.Close()
	// fmt.Printf("Done in %v\n", time.Since(start))
	return buf.Bytes()
}
```

github.com/fogleman/gg.(*Context).SetFontFace(...)
        /usr/go/pkg/mod/github.com/fogleman/gg@v1.3.0/context.go:681
github.com/psykhi/wordclouds.(*Wordcloud).setFont(0xc0001ac360, 0xfff8000000000000)
        /usr/go/pkg/mod/github.com/psykhi/wordclouds@v0.0.0-20220726053412-02b436e8666f/wordcloud.go:142 +0x15b
github.com/psykhi/wordclouds.(*Wordcloud).Place(0xc0001ac360, {{0xc0000c8a28?, 0x0?}, 0x0?, 0xc00022d968?})
        /usr/go/pkg/mod/github.com/psykhi/wordclouds@v0.0.0-20220726053412-02b436e8666f/wordcloud.go:172 +0x1a5
github.com/psykhi/wordclouds.(*Wordcloud).Draw(0xc0001ac360)
        /usr/go/pkg/mod/github.com/psykhi/wordclouds@v0.0.0-20220726053412-02b436e8666f/wordcloud.go:208 +0x99
bot/wdCloud.Rank(0xc000196030?)

**Comment by psykhi** [comment]
Hi, could you provide some code so I can reproduce?

I tried adapting your code and had no issues.

**Comment by jizizr** [comment]
> Hi, could you provide some code so I can reproduce?
> 
> I tried adapting your code and had no issues.

Sorry I retry it on my PC,It also works well .It seems my server's problem.

**Comment by jizizr** [comment]
> Hi, could you provide some code so I can reproduce?
> 
> I tried adapting your code and had no issues.

I find it will not work we input map just contain only one key-value pair.For example: 
`inputWords := map[string]int{"test": 42}`

**Comment by jizizr** [comment]
It can work when map has more the one word.
And It can work before pull#9 when met just one word in map

**Comment by psykhi** [comment]
@jizizr I think I pushed a fix to master now. Can you tell me if it's working?

**Comment by jizizr** [comment]
@psidex 
![image](https://user-images.githubusercontent.com/78908842/181411304-9a80d35c-4920-4f58-9131-993ee0fd4d82.png)

**Comment by jizizr** [comment]
It may getting too small when only have a few word .For example:
![image](https://user-images.githubusercontent.com/78908842/181411476-7634a83b-73f5-40ad-aa9d-52912aec9990.png)

**Comment by psykhi** [comment]
Thanks @jizizr ! I should have reviewed that PR better! I think it's fixed now, can you let me know?

**Comment by jizizr** [comment]
It  works well!

**Comment by psykhi** [comment]
Awesome!
I don't think adding a copyright to an image is something that belongs in a library to build wordclouds to be honest. If one wants to add that, they can  easily do it after creating the image :)
