### ISSUE TITLE
Error at go get in spatialhashmap.go

### ISSUE THREAD

**Issue by yum-yab** [psykhi/wordclouds#8]
While running go get i encountered the error: 

> go/src/github.com/psykhi/wordclouds/spatialhashmap.go:36:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values

Looked for a solution and found this [https://github.com/satori/go.uuid/issues/66#issuecomment-378848151](url)
Added it and now it builds correctly. Maybe you want to add that.
Cheers

**Comment by psykhi** [comment]
Isn't that what https://github.com/psykhi/wordclouds/issues/6 describes? If so then it's probably an issue with your gopath

**Comment by yum-yab** [comment]
Yep its the same.
